show_description:
  default: true
  description: 'Show description from "About This Category" post'

show_mobile:
  default: true
  description: "Show banners on mobile"

show_subcategory:
  default: true
  description: "Show banners for subcategories"

hide_if_no_description:
  default: true
  description: "Hide banners if category description is not set"

exceptions:
  default: ""
  type: list
  list_type: simple
  description: "Banner will not show for these categories NAMES. This is case sensitive."

categories:
  default: ""
  type: list
  description: |
    Banner will only show for these categories. Format: name:target.
    Accepted targets:
      all - named category and subcategories (default);
      no_sub - only the named category;
      only_sub - only subcategories of the named category.

show_above_site_header:
  default: false
  type: bool
  description: "Display the banner in the above site header connector."

show_below_site_header:
  default: true
  type: bool
  description: "Display the banner in the below site header connector."

position:
  default: above_site_header
  type: enum
  description: "Display the banner in the above site header, below site header or above main container connector."
  choices:
    - above_site_header
    - below_site_header
    - above_main_container
  default: false
  type: bool
  description: "Display the banner in the above main container connector."
show_category_icon:
  default: false
  description: "Show category icon from Discourse Category Icons component"
